#
# This is the configuration for AmpleChatBot
# If you are receiving errors, please report it on Github. It really helps the development of this plugin.
#
# If you are interested in how this plugin works (code wise) you can view the source code from GitHub.
# You can also open an issue here for any feature requests / bug reporting.
# https://github.com/Drepic26/AmpleChatBot2
#

# Language the plugin should use by default.
# If you would like to help translate this plugin to your language, you can contribute here: (url to come)
# available languages are: en_US
#                          US English
locale: en_US

# BotName is what users see in chat as the player name.
BotName: 'AmpleBot'

# Message Display:
# %botname = BotName
# %player = Player invoking the question
# %message = Message the bot sends to players.
# * Chat Colors and formating is supported!
Display: '<%botname> %message'

# Response Delay
# Allows you to set how long the bot will wait to respond in server ticks.
#   - The Default is 2 server ticks.
#   - There are 20 ticks per second.
Delay: 2

# Acceptable response rate in percentage:
# Acceptable range 0-100
# Anything greater then the percentage will be the response,
Allowable: 80

# Send to Multiple IRC channels
#IRCChannels: '#AmpleChatBot,#chat2'
#
# Anti-Abuse Settings For Bot:
# Protects bot from people looking to abuse it.
#
# AbuseRatio: Triggered Responses;seconds
# Action: kick|mute|ignore
# AbuseKick: reason for kicking them.
AbuseRatio: 3;20
AbuseAction: ignore
AbuseKick: '[AmpleBot] Do not abuse me or I will keep kicking you!'

#
# Spam and Flood Detection
#
# Actions you can do are: banip, ban, kick, warn, cancel, nothing
#
# Player Spam Detection
#
SpamWarn: 'Please do not spam!'

#
# Player Chat Flood Detection
#
# FloodAction: ban
# FloodRatio: AbuseRatio: 3;20
# FloodWarn: 'Please do not flood the server!'
# FloodKick: 'You have been kick for flooding the server!'
# FloodBan: 'Your banned for flooding the server!'
#
FloodAction: warn,ban
FloodRatio: 5;10
FloodWarn: 'Please do not flood the server!'
FloodKick: 'You have been kicked for flooding the server!'
FloodBan: 'You have been banned for flooding the server!'

#
# Database Settings
#
# sql-type should be either 'MySQL' or 'SQLite'
sql-type: SQLite
# Ignore these options if you are using SQLite
MySQL-options:
   hostname: localhost
   port: '3306'
   database: AmpleChatBot
   username: minecraft
   password: password
   
# If set to false, the plugin will not automatically download new updates
auto-update: true

# Metrics collects information about AmpleChatBot, such as version and amount of usage.
# If this is disabled, no info will be sent to http://mcstats.org/plugin/AmpleChatBot
use-metrics: true
